@startuml Veterinaria
skinparam classAttributeIconSize 1
Package "Excepciones" <<Rectangle>>{
    class TurnoSolapado <<Exception>>{
        + turnoSolapado(message: String)
    }
    class CancelacionFueradeTermino <<Exception>>{
        + cancelacionFueradeTermino(message: String)
    }
    class CupoLLeno <<Exception>>{
        + cupoLleno(message: String)
    }
    class VacunaVigente <<Exception>>{
        + vacunaVigente(message: String)
    }
    class MascotaNoEncontrada <<Exception>>{
        + mascotaNoEncontrada(message: String)
    }
    class VeterinarioNoDisponible <<Exception>>{
        + veterinarioNoDisponible(message: String)
    }
    class JaulaNoDisponible <<Exception>>{
        + jaulaNoDisponible(message: String)
    }
    class EspecialidadExistente <<Exception>>{
        + especialidadExistente(message: String)
    }
}

class Persona{
    # id: Long
    # nombre: String
    # apellido: String
    # telefono: String
    # email: String
    + getNombre(): String
    + getContacto(): String
    + setContacto(telefono: String, email: String): void
    + setDatosPersonales(nombre: String, apellido: String): void
}

class Cliente{
    + getMascotas(): List<Mascota>
    + registrarMascota(mascota: Mascota): void

}
class Veterinario{
    - matricula: String 
    - especialidades: List<Especialidad>
    - diasDisponibles: List<String>
    + getEspecialidad(): String
    + getDiasDisponibles(): List<String>
    + agregarEspecialidad(especialidad: Especialidad): void
    + validarDisponibilidad(fecha: LocalDate, hora: LocalTime, duracion: double): boolean
    + setMatricula(matricula: String): void

}
class Especialidad{
    - nombreEspecialidad: String
    - descripcion: String
    + getDetalles(): String
    + setDetalles(nombreEspecialidad: String, descripcion: String): void
    + registrarEspecialidad(veterinario: Veterinario): void
}

class Mascota{
    - id: Long
    - nombreMascota : String
    - especie : String
    - raza : String
    - fechaNacimiento : LocalDate
    - dueno: Cliente
    - numeroFicha: Long
    + Mascota(nombreMascota: String, especie: String, raza: String, fechaNacimiento: LocalDate, dueno: Cliente)
    + getDetallesMascota(): String
    + obtenerEdad(): int
    + obtenerProximaVacunacion(): Vacuna
    + agregarTurno(turno: Turno): void 
    + obtenerHistoriaClinica():List<Turno>
    + getDueno(): Cliente
    + setDatosMascota(nombreMascota: String, especie: String, raza: String, fechaNacimiento: LocalDate): void
    + registrarAplicacion(vacun: Vacuna, fechaAplicacion: LocalDate): void
    + validarAplicacion(vacuna: Vacuna, fechaAplicacion: LocalDate): boolean

}

class Turno{
    - id: Long
    - fecha: LocalDate
    - hora: LocalTime
    - servicios: List<Servicio>
    - veterinario: Veterinario
    - mascota: Mascota
    - estado: EstadoTurno
    + getDetalles(): String
    + getEstado(): EstadoTurno
    + actualizarEstado(nuevoEstado: EstadoTurno): void
    + agregarServicio(servicio: Servicio): void
    + calcularCostoTotal(): Double
    + cancelarTurno(fechahoraCancelacion: LocalDateTime) throws CancelacionFueradeTermino
    + confirmarTurno(): void
    + atenderTurno(): void

}

enum EstadoTurno{
    PENDIENTE,
    CONFIRMADO,
    ATENDIDO,
    CANCELADO
}

class Vacuna{
    - id: Long
    - nombreComercial: String 
    - enfermedad: String
    - periodicidad: int
    + getDetallesVacuna(): String
    + calcularProximaAplicacion(): LocalDate

}

class Vacunacion{
    - vacunaAplicada: Vacuna
    + getDetallesVacunacion(): String
    + setfechaAplicacion(fechaAplicacion: LocalDate): void

}

abstract class Servicio{
    # id: Long
    # turno: Turno 
    # tipoServicio: TipoServicio
    # precioHistorico: Double
    + getDetallesServicio(): String
    + calcularCosto(): Double 
}

class TipoServicio{
    - nombreDescriptivo: String
    - precioBase: Double
    - duracion: double  
    - limiteCupoDiario: Integer
    + validarCupo(fecha: LocalDate, ocupacionActual: int): boolean
    + setDetalles(nombreDescriptivo: String, precioBase: Double, duracion: double, limiteCupoDiario: Integer): void
    + calcularCosto(): Double
    + getDetallesTipoServicio(): String

}
class Consulta{
    - motivoConsulta: String
    - diagnostico: String
    - tratamiento: String
    + getDetallesConsulta(): String
}
class Peluqueria{
    - tipoCorte: String
    - observaciones: String
    + getDetallesPeluqueria(): String
}
class Guarderia{
    - jaulaAsignada: String
    - alimentacionEspecifica: String
    - requiereActividad: boolean
    - observaciones: String 
    + getDetallesGuarderia(): String
    + registrarReserva(mascota: Mascota, fechaIngreso: LocalDate, jaulaAsignada: String): void
}


'Relaciones
Persona <|-- Cliente :  es un <
Persona <|-- Veterinario : es un <
Servicio <|-- Vacunacion : es un <
Servicio <|-- Consulta : es un <
Servicio <|-- Peluqueria : es un <
Servicio <|-- Guarderia : es un <

Especialidad "*" <--- "1" Veterinario: tiene una <
Veterinario "1" ---> "*" Turno: atiende >
Cliente "1"---> "*" Mascota: tiene un >
Mascota "1"---> "*" Turno: tiene un >
Turno "1" ---> "1" EstadoTurno: tiene un >
Turno "1" <--- "*" Servicio:  se incluye <
Vacunacion "*" ---> "1" Vacuna: se aplica >
TipoServicio "1" ---> "*" Servicio: se incluye >

@enduml